# Generated by Django 4.0.4 on 2022-05-09 19:19

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name='Joe Silver', email="joe@email.com", document='22342342', phone='00000000').save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
    
